### ISSUE TITLE
Cannot clone repository

### ISSUE THREAD

**Issue by DrSeussFreak** [timhaak/docker-mylar#1]
git clone git@github.com:timhaak/docker-mylar.git
Cloning into 'docker-mylar'...
Warning: Permanently added the RSA host key for IP address '192.30.252.131' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by DrSeussFreak** [comment]
Meant to add that I just switched it to "git clone https://github.com/timhaak/docker-mylar.git" and all is well

**Comment by timhaak** [comment]
Hi

Actually github who changed somethings.

I've updated the readme to point to https://github.com/timhaak/docker-mylar.git
